docpdf/urls.py
from django.urls import path
from . import views
app_name = "docpdf"
urlpatterns = [
    path('avispoursuiteetude/tous/', views.avispoursuitetous, name='avispoursuitetous'),
    
    path('avispoursuiteetude/<int:id>/', views.avispoursuite, name='avispoursuite'),



]

etudiant/urls.py
from django.urls import path,re_path
from . import views
app_name = "etudiant"
urlpatterns = [
    path('', views.indexetudiant, name='index'),
    re_path(r"^(?P<alt>(alt|nonalt|neu|redoubl))/$",views.listeetudiant, name='liste'),
    path('<int:id>/', views.vueetudiant, name='vue'),
    path('add/', views.addetudiant, name ='addetudiant'),
    path('inscriptiondiplome/', views.addinscriptiondipl, name ='addinscriptiondipl'),
    path('inscriptionmat/<int:id>/', views.addinscriptionmat, name ='addinscriptionmat'),
    path('admin',views.indexetudiantadmin, name="indexetudiantadmin"),

] 

gestiondejury/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('etudiants/',include('etudiant.urls')),
    path('comptes/', include('comptes.urls')),
    path('matieres/', include('matiere.urls')),
    path('adminjury/', include('adminjury.urls')),
    path('jury/', include('jury.urls')),
    path('excel/',include('tableurxl.urls')),
    path('diplome/',include('diplome.urls')),
    path('docpdf/',include('docpdf.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
]

matiere/urls.py
from django.urls import path,re_path
from . import views
app_name = "matiere"
urlpatterns = [
    path('', views.indexmatiere, name='index'),
    path('notes/<str:code>', views.notes,name='notes'),
    path('editnotes/<str:code>/<int:etudiant>', views.editnotes,name='editnotes'),
    re_path(r'^editnotesmatiere/(?P<code>KM[A-Z]{4}\d{2})/(?P<alt>(alt|nonalt))/(?P<etudiantalpha>\d+)$',views.editnotesmatiere,name = 'editnotesmatiere'),
    path("excelnotes/<str:sem>",views.listematexcel,name="listematexcel")

]

etudiant/models.py
from django.db import models
from diplome.models import Diplome,Anneeuniv
from matiere.models import Matiere


# Create your models here.
class Etudiant(models.Model):
    class Genre(models.TextChoices):
        Monsieur = 'M.'
        Madame = 'Mme'



    id = models.AutoField(primary_key=True)
    numero = models.IntegerField(unique=True)
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=255)
    genre = models.CharField(choices=Genre.choices, max_length=5)

    datedenaissance = models.DateField( null=True)
   


    photo = models.ImageField(upload_to='photos/', default='photos/image.jpg')

   

    def __str__(self):
        return self.nom+' '+ self.prenom
    
class Inscriptiondiplome(models.Model):
    class Statut(models.TextChoices):
        Admis = 'ADM'
        Admis_Jury = 'ADJ'
        Ajourne = 'AJ'
        SansResultat ='Sresul'
    class AvisPoursuite(models.TextChoices):
        TRESFAVORABLE ='TF', 'Avis très favorable'
        FAVORABLE = 'FA', 'Avis favorable'
        RESERVE = 'RE', 'Avis réservé'
        DEFAVORABLE = 'DE', 'Avis défavorable'
    class Erasmus(models.TextChoices):
        ENTRANT='E','Entrant'
        SORTANT = 'S','Sortant'

    etudiant = models.ForeignKey(Etudiant,on_delete=models.CASCADE, related_name="inscriptions")
    diplome = models.ForeignKey(Diplome,on_delete=models.CASCADE, related_name="inscriptions")
    anneeuniv=models.ForeignKey(Anneeuniv,on_delete=models.CASCADE, related_name="inscriptions")
    noteSem1=models.FloatField(null=True,default=None,blank = True)
    rangSem1=models.IntegerField(null=True)
    noteSem2=models.FloatField(null=True,default=None,blank = True)
    rangSem2=models.IntegerField(null=True)
    noteAnnee=models.FloatField(null=True,default=None,blank = True)
    rangAnnee=models.IntegerField(null=True,blank = True)
    statutDipl = models.CharField(null=True,blank = True,choices=Statut.choices, max_length=6,default =None)
    datedecisionDipl = models.DateTimeField(null=True,blank = True,default=None)
    statutS1 = models.CharField(null=True,blank = True,choices=Statut.choices, max_length=6,default =None)
    datedecisionS1 = models.DateTimeField(null=True,blank = True,default=None)
    statutS2 = models.CharField(null =True,blank = True,choices=Statut.choices, max_length=6,default =None)
    datedecisionS2 = models.DateTimeField(null=True,blank = True,default=None)
    avispoursuite = models.CharField(choices=AvisPoursuite.choices, 
                                     max_length=2,null = True,blank = True)
    erasmus = models.CharField(choices=Erasmus.choices,
                                     max_length=1,null = True, blank=True)
    iaL2 = models.BooleanField(default=False)
    alternant = models.BooleanField(default=False)
    neu = models.BooleanField(default=False)
    tierstemps = models.BooleanField(default=False)
    rse = models.BooleanField(default=False)
    redoublant =models.BooleanField(default=False)
    Nmoinsun = models.CharField(max_length=255, null=True,blank=True)

    def __str__(self):
        return self.anneeuniv.anneeuniv + ' : ' +self.etudiant.nom +' '+self.diplome.nom      

class Inscriptionmat(models.Model):
    class Statut(models.TextChoices):
        Admis = 'ADM'
        Admis_Jury = 'ADJ'
        Ajourne = 'AJ'
        SansResultat ='Sresul'
    
    inscriptiondiplome = models.ForeignKey(Inscriptiondiplome,on_delete=models.CASCADE, null=True,)
    matiere = models.ForeignKey(Matiere,on_delete=models.CASCADE, related_name="matieres",related_query_name='mat')

    notecc1=models.FloatField(null=True,blank=True)
    notecc2=models.FloatField(null=True,blank=True)
    notecc3=models.FloatField(null=True,blank=True)
    moyenne=models.FloatField(null=True,blank=True)
    pointjury=models.FloatField(null=True,blank=True)
    statut = models.CharField(null = True,blank=True,choices=Statut.choices, max_length=6)
    decisionmat = models.DateTimeField(null=True,blank=True,)
    rang=models.IntegerField(null=True,blank=True,)

    def __str__(self):
        return self.inscriptiondiplome.anneeuniv.anneeuniv + ' : ' +self.inscriptiondiplome.etudiant.nom +' '+self.matiere.nom

etudiant/forms.py
from django import forms
from .models import Etudiant,Inscriptiondiplome
from matiere.models import Matiere

class EtudiantForm(forms.ModelForm):


    class Meta:
        model=Etudiant
        fields='__all__'

class InscriptiondiplForm(forms.ModelForm):


    class Meta:
        model=Inscriptiondiplome
        fields=["etudiant","diplome","anneeuniv"]


class MatiereSelectionForm(forms.Form):
    matieres = forms.ModelMultipleChoiceField(
        queryset=Matiere.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Selection des matières")
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['matieres'].queryset=Matiere.objects.all()
        self.initial['matieres'] = Matiere.objects.all()

etudiant/views.py
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from .models import Inscriptionmat,Inscriptiondiplome,Etudiant
from diplome.models import Anneeuniv,Diplome
from matiere.models import Matiere
from .forms import EtudiantForm,InscriptiondiplForm,MatiereSelectionForm
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


@login_required
def indexetudiant(request):
    anneeunivsession = request.session.get('anneesession')

    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession)  
    templateData = {}
    templateData ['titre']= "Etudiants"
    ListeInscritDiplome = Inscriptiondiplome.objects.filter(anneeuniv=anneeuniv).order_by('etudiant__nom','etudiant__prenom')
    templateData ['inscritdiplome']= ListeInscritDiplome
    templateData['anneeuniv'] = anneeuniv
    return render (request,'etudiant/listeetudiant.html'
                  ,{'templateData': templateData} )


@permission_required('etudiant.change_etudiant', raise_exception=True)
@login_required
def addetudiant(request):
    if request.method=='POST':
        form=EtudiantForm(request.POST)
        if form.is_valid():
            etudiant=form.save()
            
            return redirect('etudiant:addinscriptiondipl')
    else:
        form=EtudiantForm()
    templateData = {}
    templateData ['titre']= "Création d'un etudiant "
    return render(request,'etudiant/creeretudiant.html',{'form': form, 'templatedata':templateData})


@permission_required('etudiant.change_etudiant', raise_exception=True)
@login_required
def addinscriptiondipl(request):
    if request.method=='POST':
        form=InscriptiondiplForm(request.POST)
        if form.is_valid():
            etudiant =form.cleaned_data['etudiant']

            form.save()
            return redirect('etudiant:addinscriptionmat',id = etudiant.id)
    else:
        form=InscriptiondiplForm()
    templateData = {}
    templateData ['titre']= "Inscription d'un etudiant "

    return render(request,'etudiant/inscriptiondipletudiant.html',{'form': form, 'templatedata':templateData})

@permission_required('etudiant.change_etudiant', raise_exception=True)
@login_required
def addinscriptionmat(request,id):
    etudiant = Etudiant.objects.get(id=id)
    anneeunivinscrit = Anneeuniv.objects.get(anneeuniv=request.session.get('anneesession')) 
    diplome = Diplome.objects.get(id=1)
    existe =Inscriptiondiplome.objects.filter(etudiant=etudiant,anneeuniv=anneeunivinscrit,diplome=diplome).exists()
    if existe:
        if request.method == "POST":
            form = MatiereSelectionForm(request.POST)
            if form.is_valid():
                inscriptiondipl = Inscriptiondiplome.objects.get(etudiant=etudiant,anneeuniv=anneeunivinscrit,diplome=diplome)

                matieres_selectionnees = form.cleaned_data['matieres']
            
                listematiere =Matiere.objects.all()
                for matiere in listematiere:

                    existeInscrMat=Inscriptionmat.objects.filter(inscriptiondiplome=inscriptiondipl,matiere=matiere).exists()

                    if (not existeInscrMat) and (matiere in matieres_selectionnees):
                        print(matiere.nom)
                        inscriptionmatiere = Inscriptionmat(inscriptiondiplome=inscriptiondipl,matiere=matiere)
                        inscriptionmatiere.save()
                    elif existeInscrMat and not (matiere in matieres_selectionnees):
                        inscriptionmatiere=Inscriptionmat.objects.filter(inscriptiondiplome=inscriptiondipl,matiere=matiere)
                        inscriptionmatiere.delete()
                return redirect('etudiant:vue',id=etudiant.id)
                        


        else:
            form = MatiereSelectionForm()
        templateData = {}
        templateData ['titre']= "Inscription matières " + etudiant.nom +" "+etudiant.prenom
        templateData ['etudiant']= etudiant 
        templateData ['annee']= anneeunivinscrit
        return render(request, "etudiant/inscriptionmat.html", {'form': form, 'templatedata':templateData})
    else:
        message = "Etudiant "+etudiant.nom+" "+etudiant.prenom+" n'est pas inscrit en "+anneeunivinscrit.anneeuniv
        messages.warning(request,message)
        return redirect('etudiant:index')




@login_required
def listeetudiant(request,alt):
    anneeunivsession = request.session.get('anneesession')

    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession)  
    templateData = {}
    templateData ['titre']= "Etudiants"
    ListeInscritDiplome = Inscriptiondiplome.objects.filter(anneeuniv=anneeuniv)
    if alt == 'alt':
        
        ListeInscritDiplome = ListeInscritDiplome.filter(alternant=True).order_by('etudiant__nom','etudiant__prenom')
    elif alt == 'neu':
        ListeInscritDiplome = ListeInscritDiplome.filter(neu=True).order_by('etudiant__nom','etudiant__prenom')

    elif alt == 'nonalt':
        ListeInscritDiplome = ListeInscritDiplome.filter(alternant=False).order_by('etudiant__nom','etudiant__prenom')
        
    elif alt == 'redoubl':
        ListeInscritDiplome = ListeInscritDiplome.filter(redoublant=True).order_by('etudiant__nom','etudiant__prenom')


    
    templateData ['inscritdiplome']= ListeInscritDiplome
    templateData['anneeuniv'] = anneeuniv
    return render (request,'etudiant/listeetudiant.html'
                  ,{'templateData': templateData} )

@login_required
def vueetudiant(request, id): 
    anneeunivsession = request.session.get('anneesession')

    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession) 
    etudiant = Etudiant.objects.get(id=id)

    anneeunivencours = Anneeuniv.objects.get(encours = True)
    listeinsdiplome = Inscriptiondiplome.objects.filter(etudiant=etudiant)
    listeinsdiplome =listeinsdiplome.order_by('anneeuniv__datedebut')
    try:
        inscridipl = Inscriptiondiplome.objects.get(etudiant=etudiant,anneeuniv=anneeuniv)

    except (ObjectDoesNotExist, ValueError, TypeError):
        inscridipl= None
    if inscridipl is not None:
        if inscridipl.alternant :
            nbreetudiants = Inscriptiondiplome.objects.filter(anneeuniv=anneeuniv,alternant = True).count()
        else :
            nbreetudiants = Inscriptiondiplome.objects.filter(anneeuniv=anneeuniv,alternant = False).count()


        
   
    ListeInscritmat =Inscriptionmat.objects.filter(inscriptiondiplome__etudiant=etudiant ,inscriptiondiplome__anneeuniv__datedebut__lte=anneeuniv.datedebut)
    if(not(anneeuniv.S2)):
        ListeInscritmat = ListeInscritmat.filter(matiere__semestre ="S5")
    ListeInscritmat = ListeInscritmat.order_by('matiere__semestre','matiere__nom','inscriptiondiplome__anneeuniv')

    templateData = {}
    templateData ['titre']= "Etudiant : " + etudiant.nom +" "+  etudiant.prenom 
    templateData ['etudiant']= etudiant  
    templateData ['listeinscritmat']=ListeInscritmat
    templateData ['insdiplome']=inscridipl
    templateData ['listeinsdiplome']=listeinsdiplome
    templateData['S2']=anneeuniv.S2 

    templateData['nbreetudiants'] = nbreetudiants
    return render (request,'etudiant/vueetudiant.html'
                  ,{'templateData': templateData} )   

@permission_required('etudiant.change_etudiant', raise_exception=True)
@login_required
def indexetudiantadmin(request):
    anneeunivsession = request.session.get('anneesession')
    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession)  
    templateData = {}
    templateData ['titre']= "Etudiants"
    ListeInscritDiplome = Inscriptiondiplome.objects.filter(anneeuniv=anneeuniv).order_by('etudiant__nom','etudiant__prenom')
    templateData ['inscritdiplome']= ListeInscritDiplome
    templateData['anneeuniv'] = anneeuniv
    return render (request,'etudiant/listeetudiantadmin.html'
                  ,{'templateData': templateData} )

etudiant/templates/etudiant/cadreetudiant.html
<div class="card">


    <img src="{{ templateData.etudiant.photo.url }}" class="card-img-top rounded" width="60">


    <div class="card-body">
        <h3 class="card-title">
            {{ templateData.etudiant.genre }}
            {{ templateData.etudiant.nom }}
            {{ templateData.etudiant.prenom }}</h3>
        <h4>{{ templateData.etudiant.numero }}</h4>

    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">ANNEE ANTERIEURE : {{ templateData.insdiplome.Nmoinsun }}
        </li>
        {% if templateData.insdiplome.iaL2 %}
        <li class="list-group-item">Emjambeur
        </li>
        {% endif %}
        {% if templateData.insdiplome.alternant %}
        <li class="list-group-item">Alternant
        </li>
        {% endif %}
        {% if templateData.insdiplome.neu %}
        <li class="list-group-item">N.E.U.
        </li>
        {% endif %}
        {% if templateData.insdiplome.redoublant %}
        <li class="list-group-item">Redoublant
        </li>
        {% endif %}
    </ul>
    <h4>Inscription L3 GMA</h4>
    <ul>
        {% for insdipl in templateData.listeinsdiplome %}
        <li>{{ insdipl.anneeuniv.anneeuniv }}</li>
        {% if insdipl.erasmus is not None %}
        ERASMUS : {{ insdipl.get_erasmus_display }}
        {% endif %}
        {% endfor %}
    </ul>
    <div class="card-body">
        <h4>Avis de poursuite d'étude</h4>

        {{ templateData.insdiplome.get_avispoursuite_display }}

        {% if perms.gdjury.add_etudiant and templateData.juryS5 %}
        <a href="{% url 'docpdf:avispoursuite' templateData.etudiant.id %}" class="btn btn-primary btn-lg" role="button"
            target="_blank">Document Avis</a>

        {% endif %}

    </div>
</div>

etudiant/templates/etudiant/creeretudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-5 ">
    <div class="container">
        <h2>Créer un nouvel étudiant</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enregistrer</button>
        </form>
    </div>
</div>









{% endblock content %}

etudiant/templates/etudiant/inscriptiondipletudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-5 ">
    <div class="container">
        <h2>Inscription d'un étudiant</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Enregistrer</button>
        </form>
    </div>
</div>









{% endblock content %}

etudiant/templates/etudiant/inscriptionmat.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-5 ">
    <div class="container">
        <h2>Inscription matières de {{ templatedata.etudiant.genre }}
            {{ templatedata.etudiant.nom }} {{templatedata.etudiant.prenom }}</h2>
        <h2>Année universitaire : {{ templatedata.annee.anneeuniv }}</h2>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Valider</button>
        </form>
    </div>
</div>

{% endblock content %}

etudiant/templates/etudiant/listeetudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>Liste des étudiants {{ templateData.anneeuniv }}</h2>
                <hr />
            </div>
        </div>
        <div class="row">
            {% for inscription in templateData.inscritdiplome %}
            <div class="col-md-4 col-lg-3 mb-2">
                <div class="p-2 card align-items-center pt-4">

                    <img src="{{ inscription.etudiant.photo.url }}" class="card-img-top rounded img-card-200">

                    <div class="car.d-body text-center">
                        {% if inscription.alternant %}
                        <a href="{% url 'etudiant:vue' id=inscription.etudiant.id %}" class="btn bg-info text-white">
                            {{ inscription.etudiant.genre }} {{ inscription.etudiant.nom }}
                            {{ inscription.etudiant.prenom }} <br>{{ inscription.etudiant.numero }}
                        </a>
                        {% elif inscription.neu %}
                        <a href="{% url 'etudiant:vue' id=inscription.etudiant.id %}" class="btn bg-warning text-white">
                            {{ inscription.etudiant.genre }} {{ inscription.etudiant.nom }}
                            {{ inscription.etudiant.prenom }} <br>{{ inscription.etudiant.numero }}
                        </a>
                        {% else %}
                        <a href="{% url 'etudiant:vue' id=inscription.etudiant.id %}" class="btn bg-primary text-white">
                            {{ inscription.etudiant.genre }} {{ inscription.etudiant.nom }}
                            {{ inscription.etudiant.prenom }} <br>{{ inscription.etudiant.numero }}
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

etudiant/templates/etudiant/vueetudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-5 ">
    <div class="container">
        <div class="row">
            <div class="col-3 align-self-start">
                {% include "etudiant/cadreetudiant.html" %}
            </div>


            <div class="col align-self-start">

                <table class="table">
                    <thead>
                        <tr>
                            <th> Semestre</th>
                            <th>Moyenne</th>
                            <th>Statut</th>
                            <th>Rang</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>
                                <h4>S5</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.noteSem1|floatformat:2 }}</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.statutS1 }} </h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.rangSem1 }}/{{ templateData.nbreetudiants }}</h4>
                            </th>
                        </tr>
                        {% if templateData.S2 %}
                        <tr>
                            <th>
                                <h4>S6</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.noteSem2|floatformat:2 }}</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.statutS2 }} </h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.rangSem2 }}/{{ templateData.nbreetudiants }} </h4>
                            </th>
                        </tr>
                        <tr>
                            <th>
                                <h4>Année</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.noteAnnee|floatformat:2 }}</h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.statutDipl }} </h4>
                            </th>
                            <th>
                                <h4>{{ templateData.insdiplome.rangAnnee }}</h4>
                            </th>
                        </tr>

                    </tbody>
                </table>
                <h3>Semestre 6</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Code</th>
                            <th scope="col">Matière</th>
                            <th scope="col">Note CC1</th>
                            <th scope="col">Note CC2</th>
                            <th scope="col">Note CC3</th>
                            <th scope="col">Moyenne</th>
                            <th scope="col">Statut</th>
                            <th scope="col">Rang</th>
                            <th scope="col">Année universitaire</th>

                        </tr>
                    </thead>
                    <tbody>

                        {% for inscritmat in templateData.listeinscritmat %}
                        {% if inscritmat.matiere.semestre == 'S6' %}
                        {% if inscritmat.moyenne is None %}
                        <tr>
                            {% elif inscritmat.moyenne >= 10 %}
                        <tr class="table-success">
                            {% elif inscritmat.moyenne >= 7 %}
                        <tr class="table-warning">
                            {% else %}
                        <tr class="table-danger">
                            {% endif %}
                            <th scope="row">
                                {% if perms.gestiondejury.change_etudiant %}
                                <a class="btn btn-success btn-sm"
                                    href="{% url 'matiere:editnotes' inscritmat.matiere.codeapogee inscritmat.inscriptiondiplome.etudiant.id %}"
                                    role="button">
                                    {{ inscritmat.matiere.codeapogee }}</a>
                                {% else %}

                                {{ inscritmat.matiere.codeapogee }}

                                {% endif %}
                            </th>



                            <td>{{ inscritmat.matiere.nom }}</td>
                            <td>{{ inscritmat.notecc1|floatformat:2 }}</td>
                            <td>{{ inscritmat.notecc2|floatformat:2 }}</td>
                            <td>{{ inscritmat.notecc3|floatformat:2 }}</td>
                            <td class="fw-bold">{{ inscritmat.moyenne|floatformat:2}}</td>
                            <td>{{ inscritmat.statut }}</td>
                            <td>{{ inscritmat.rang }}</td>

                            <td>{{ inscritmat.inscriptiondiplome.anneeuniv.anneeuniv }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}

                    </tbody>
                </table>
                {% endif %}
                <h3>Semestre 5</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Code</th>
                            <th scope="col">Matière</th>
                            <th scope="col">Note CC1</th>
                            <th scope="col">Note CC2</th>
                            <th scope="col">Note CC3</th>
                            <th scope="col">Moyenne</th>
                            <th scope="col">Statut</th>
                            <th scope="col">Rang</th>
                            <th scope="col">Année universitaire</th>

                        </tr>
                    </thead>
                    <tbody>

                        {% for inscritmat in templateData.listeinscritmat %}
                        {% if inscritmat.matiere.semestre == 'S5' %}
                        {% if inscritmat.moyenne is None %}
                        <tr>
                            {% elif inscritmat.moyenne >= 10 %}
                        <tr class="table-success">
                            {% elif inscritmat.moyenne >= 7 %}
                        <tr class="table-warning">
                            {% else %}
                        <tr class="table-danger">
                            {% endif %}
                            <th scope="row">
                                {% if perms.gestiondejury.change_etudiant %}
                                <a class="btn btn-success btn-sm"
                                    href="{% url 'matiere:editnotes' inscritmat.matiere.codeapogee inscritmat.inscriptiondiplome.etudiant.id %}"
                                    role="button">
                                    {{ inscritmat.matiere.codeapogee }}</a>
                                {% else %}

                                {{ inscritmat.matiere.codeapogee }}

                                {% endif %}
                            </th>



                            <td>{{ inscritmat.matiere.nom }}</td>
                            <td>{{ inscritmat.notecc1|floatformat:2 }}</td>
                            <td>{{ inscritmat.notecc2|floatformat:2 }}</td>
                            <td>{{ inscritmat.notecc3|floatformat:2 }}</td>
                            <td class="fw-bold">{{ inscritmat.moyenne|floatformat:2}}</td>
                            <td>{{ inscritmat.statut }}</td>
                            <td>{{ inscritmat.rang }}</td>

                            <td>{{ inscritmat.inscriptiondiplome.anneeuniv.anneeuniv }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row p-2">


        <div class="col-3 ">
            <a class="btn btn-primary btn-sm" href="{% url 'etudiant:index'  %}" role="
                button">Retour</a>
        </div>


    </div>
</div>
</div>






{% endblock content %}