gestiondejury/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('etudiants/',include('etudiant.urls')),
    path('comptes/', include('comptes.urls')),
    path('matieres/', include('matiere.urls')),
    path('adminjury/', include('adminjury.urls')),
    path('jury/', include('jury.urls')),
    path('excel/',include('tableurxl.urls')),
    path('diplome/',include('diplome.urls')),
    path('docpdf/',include('docpdf.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
]

matiere/urls.py
from django.urls import path,re_path
from . import views
app_name = "matiere"
urlpatterns = [
    path('', views.indexmatiere, name='index'),
    path('notes/<str:code>', views.notes,name='notes'),
    path('editnotes/<str:code>/<int:etudiant>', views.editnotes,name='editnotes'),
    re_path(r'^editnotesmatiere/(?P<code>KM[A-Z]{4}\d{2})/(?P<alt>(alt|nonalt))/(?P<etudiantalpha>\d+)$',views.editnotesmatiere,name = 'editnotesmatiere'),
    path("excelnotes/<str:sem>",views.listematexcel,name="listematexcel")

]

tableurxl/urls.py
from django.urls import path
from . import views

app_name = "tableurxl"

urlpatterns = [
    path('upload/', views.upload_excel, name='upload_excel'),
    path('etudiants/', views.upload_excelinsdiplome, name='upload_excelinsdiplome'),
    path('entreenotes/<str:codemat>', views.upload_excelnotesmat, name='uploadexcelnotesmat'),
    path('entreenotes2/<str:codemat>', views.upload_excelnotesmat2, name='uploadexcelnotesmat2'),
]

matiere/models.py
from django.db import models

from diplome.models import Anneeuniv


class Matiere(models.Model):

    
    codeapogee = models.CharField(max_length=25, unique = True)
    nom = models.CharField(max_length=255)
    semestre = models.CharField(max_length=2)
    coefcc1 = models.IntegerField()
    coefcc2 = models.IntegerField()
    coefcc3 = models.IntegerField()

    def __str__(self):
        return self.nom
    
# Create your models here.
class Nbreinscrit(models.Model):
    matiere =models.ForeignKey(Matiere, on_delete=models.CASCADE)
    anneeuniv=models.ForeignKey(Anneeuniv, on_delete=models.CASCADE)
    nbrInscrit=models.IntegerField()
    alt=models.BooleanField()

matiere/forms.py
from django import forms


class CCForm(forms.Form):
    CC1 = forms.FloatField(
        label ="CC1",
        min_value=0.0,
        max_value=20.0,
        required=False)
    CC2 = forms.FloatField(
        label ="CC2",
        min_value=0.0,
        max_value=20.0,
        required=False)    
    CC3 = forms.FloatField(
        label ="CC3",
        min_value=0.0,
        max_value=20.0,
        required=False)
    ADJ = forms.BooleanField(
        label="ADJ",
        required=False)

    
    def __init__(self, *args, **kwargs):
        inscrimat = kwargs.pop('inscrimat', None)
        super().__init__(*args, **kwargs)
        if inscrimat:
            self.fields['CC1'].initial = inscrimat.notecc1
            self.fields['CC2'].initial = inscrimat.notecc2
            self.fields['CC3'].initial = inscrimat.notecc3
                       
            

matiere/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib import messages
from .models import Matiere
from diplome.models import Anneeuniv
from etudiant.models import Inscriptionmat,Etudiant,Inscriptiondiplome
from .forms import CCForm
from services.calcul import  moyenneMat,calculderang

import  datetime

# Create your views here.

@login_required
def indexmatiere(request):
    templateData = {}
    templateData ['titre']= "Matiere"
    ListeMatiereS5 = Matiere.objects.filter(semestre='S5')
    ListeMatiereS6 = Matiere.objects.filter(semestre='S6')
    templateData ['matiereS5']= ListeMatiereS5
    templateData ['matiereS6']= ListeMatiereS6

    return render (request,'matiere/listematiere.html'
                  ,{'templateData': templateData} )

@login_required
def notes(request,code):
    matiere = Matiere.objects.get(codeapogee=code)
    anneeunivsession = request.session.get('anneesession')

    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession)  

    alt = request.GET.get('alt','false').lower()=='true'
    ListeInscritmat =Inscriptionmat.objects.filter(matiere=matiere ,inscriptiondiplome__anneeuniv=anneeuniv)
    if alt :
        ListeInscritmat=ListeInscritmat.filter(inscriptiondiplome__alternant=alt)
    ListeInscritmat = ListeInscritmat.exclude(moyenne__isnull = True)
    ListeInscritmat = ListeInscritmat.order_by('-moyenne')
    templateData = {}
    templateData ['titre']= "Notes: " + matiere.nom
    templateData ['matiere']= matiere  
    templateData ['listeinscritmat']=ListeInscritmat
    return render (request,'matiere/notesmatiere.html'
                  ,{'templateData': templateData} ) 

@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def editnotes(request,code,etudiant):
    matiere = Matiere.objects.get(codeapogee=code)
    anneeunivsession = request.session.get('anneesession')
    anneeuniv =get_object_or_404(Anneeuniv,anneeuniv=anneeunivsession)  
    etudiant= Etudiant.objects.get(id=etudiant)
    inscritmat = get_object_or_404(Inscriptionmat, inscriptiondiplome__etudiant = etudiant,matiere = matiere,inscriptiondiplome__anneeuniv =  anneeuniv)
   # inscridipl = Inscriptiondiplome.objects.get(etudiant=etudiant,anneeuniv=anneeunivencours)
    if request.method == 'POST':
        notesCCform = CCForm(request.POST)

        if notesCCform.is_valid():
            # Récupérer les valeurs du formulaire
            cc1 = notesCCform.cleaned_data['CC1']
            cc2 = notesCCform.cleaned_data['CC2']
            cc3 = notesCCform.cleaned_data['CC3']
            matiere = Matiere.objects.get(codeapogee=code)



            inscritmat.notecc1 = cc1
            inscritmat.notecc2 = cc2
            inscritmat.notecc3 = cc3
            inscritmat.moyenne=moyenneMat(inscritmat)
            if notesCCform.cleaned_data['ADJ']:
                inscritmat.statut = "ADJ"
                inscritmat.decisionmat = datetime.datetime.now()
            inscritmat.save()
            if inscritmat.moyenne is not None:
                if inscritmat.moyenne>=10:
                    inscritmat.statut = "ADM"
                elif inscritmat.statut != "ADJ":
                    inscritmat.statut = "AJ"
            
            if inscritmat.inscriptiondiplome.alternant:
                listeInscrimat =Inscriptionmat.objects.filter(inscriptiondiplome__anneeuniv=anneeuniv,matiere=matiere,inscriptiondiplome__alternant=True)
             
            else:

                listeInscrimat =Inscriptionmat.objects.filter(inscriptiondiplome__anneeuniv=anneeuniv,matiere=matiere,inscriptiondiplome__alternant=False)
           
            calculderang(listeInscrimat)
            
            messages.success(request, "Notes de "+str(matiere.nom)+" "+str(etudiant.nom) + " "+str(etudiant.prenom)+ " changées")
            return redirect('etudiant:vue',id = etudiant.id)
    else :
        notesCCform = CCForm(inscrimat = inscritmat)
            


    templateData = {}
    templateData ['titre']= "Notes: " + matiere.nom
    templateData ['matiere']= matiere  
    templateData ['etudiant']=etudiant
    return render (request,'matiere/editnotes.html'
                  ,{'templateData': templateData,'notesCCform':notesCCform} ) 


@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def editnotesmatiere(request,code,alt,etudiantalpha):
    etudiantalpha =int(etudiantalpha)
    matiere = Matiere.objects.get(codeapogee=code)
    anneunivencours = Anneeuniv.objects.get(encours = True)
    ListeInscritmat =Inscriptionmat.objects.filter(matiere=matiere,inscriptiondiplome__anneeuniv=anneunivencours )

    if alt =="alt":
         ListeInscritmat =  ListeInscritmat.filter(inscriptiondiplome__alternant=True).order_by('inscriptiondiplome__etudiant__nom','inscriptiondiplome__etudiant__prenom')

    else:
         ListeInscritmat =  ListeInscritmat.filter(inscriptiondiplome__alternant=False).order_by('inscriptiondiplome__etudiant__nom','inscriptiondiplome__etudiant__prenom')

    inscritmat =  ListeInscritmat[etudiantalpha-1]
    if request.method == 'POST':
        notesCCform = CCForm(request.POST)

        if notesCCform.is_valid():
            # Récupérer les valeurs du formulaire
            cc1 = notesCCform.cleaned_data['CC1']
            cc2 = notesCCform.cleaned_data['CC2']
            cc3 = notesCCform.cleaned_data['CC3']
            matiere = Matiere.objects.get(codeapogee=code)
            inscritmat.notecc1 = cc1
            inscritmat.notecc2 = cc2
            inscritmat.notecc3 = cc3
            inscritmat.moyenne=moyenneMat(inscritmat)
            inscritmat.save()
            messages.success(request, "Notes de "+str(matiere.nom)+" "+str(inscritmat.inscriptiondiplome.etudiant.nom) +
                              " "+str(inscritmat.inscriptiondiplome.etudiant.prenom)+ " changées")
           
    else :
        notesCCform = CCForm(inscrimat = inscritmat)
            


    templateData = {}
    templateData ['titre']= "Notes: " + matiere.nom
    templateData ['matiere']= matiere  
    templateData ['etudiant']= inscritmat.inscriptiondiplome.etudiant
    templateData ['rangalpha']= etudiantalpha
    templateData['alternant']=inscritmat.inscriptiondiplome.alternant
    
    return render (request,'matiere/editnotesmatiere.html'
                  ,{'templateData': templateData,'notesCCform':notesCCform} ) 

@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def listematexcel(request,sem):
    templateData = {}
    templateData ['titre']= "Liste Matiere Excel"
    ListeMatiere = Matiere.objects.filter(semestre=sem)

    templateData ['matiere']= ListeMatiere


    return render (request,'matiere/listematiereexcel.html'
                  ,{'templateData': templateData} )

matiere/templates/matiere/editnotes.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2> {{ templateData.matiere.codeapogee }} : {{ templateData.matiere.nom }}</h2>
                <h2>{{ templateData.etudiant.nom }} {{ templateData.etudiant.prenom }}</h2>
                <hr />
            </div>
        </div>
        <div class="row">
            <h1>Entrez les notes de CC</h1>
            <form method="post">
                {% csrf_token %}
                {{ notesCCform.as_p }}
                <button type="submit">Entrez</button>
            </form>


        </div>


    </div>



</div>
{% endblock content %}

matiere/templates/matiere/editnotesmatiere.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2> {{ templateData.matiere.codeapogee }} : {{ templateData.matiere.nom }}</h2>
                <h2>{{ templateData.etudiant.nom }} {{ templateData.etudiant.prenom }} </h2>

                <hr />
            </div>
        </div>
        <div class="row">
            <h1>Entrez les notes de CC</h1>
            <form method="post">
                {% csrf_token %}
                {{ notesCCform.as_p }}
                <button type="submit">Entrez</button>
            </form>


        </div>

        {% if templateData.alternant %}
        <a class="btn btn-primary btn-sm mt-3"
            href="{% url 'matiere:editnotesmatiere' templateData.matiere.codeapogee 'alt' templateData.rangalpha|add:1 %}"
            role="button">Suivant</a>

        {% else %}
        <a class="btn btn-primary btn-sm mt-3"
            href="{% url 'matiere:editnotesmatiere' templateData.matiere.codeapogee 'nonalt' templateData.rangalpha|add:1 %}"
            role="button">Suivant</a>
        {% endif %}
    </div>



</div>
{% endblock content %}

matiere/templates/matiere/listematiere.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>Liste des matieres</h2>
                <hr />
            </div>
        </div>
        <div class="row">
            <h3>Matières S5</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Code APOGEE

                        </th>
                        <th scope="col">nom</th>
                        <th scope="col">CC1</th>
                        <th scope="col">CC2</th>
                        <th scope="col">CC3</th>

                    </tr>
                </thead>
                {% for matiere in templateData.matiereS5 %}
                <tr>

                    <th scope="row">
                        <a href="{% url 'matiere:notes' code=matiere.codeapogee  %}" class="btn bg-success text-white">
                            {{ matiere.codeapogee }}
                        </a>
                    </th>
                    <td>{{ matiere.nom }}</td>
                    <td>{{ matiere.coefcc1 }}</td>
                    <td>{{ matiere.coefcc2 }}</td>
                    <td>{{ matiere.coefcc3 }}</td>

                </tr>
                {% endfor %}

            </table>

        </div>
        <div class="row">
            <h3>Matières S6</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Code APOGEE</th>
                        <th scope="col">nom</th>
                        <th scope="col">CC1</th>
                        <th scope="col">CC2</th>
                        <th scope="col">CC3</th>
                    </tr>
                </thead>
                {% for matiere in templateData.matiereS6 %}
                <tr>
                    <th scope="row"><a href="{% url 'matiere:notes' code=matiere.codeapogee  %}"
                            class="btn bg-success text-white">
                            {{ matiere.codeapogee }}
                        </a></th>
                    <td>{{ matiere.nom }}</td>
                    <td>{{ matiere.coefcc1 }}</td>
                    <td>{{ matiere.coefcc2 }}</td>
                    <td>{{ matiere.coefcc3 }}</td>
                </tr>
                {% endfor %}

            </table>

        </div>

    </div>
</div>
{% endblock content %}

matiere/templates/matiere/listematiereexcel.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>Liste des matieres</h2>
                <hr />
            </div>
        </div>
        <div class="row">
            <h3>Matières </h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Code APOGEE

                        </th>
                        <th scope="col">nom</th>
                        <th scope="col">CC1</th>
                        <th scope="col">CC2</th>
                        <th scope="col">CC3</th>

                    </tr>
                </thead>
                {% for matiere in templateData.matiere %}
                <tr>

                    <th scope="row">
                        <a href="{% url 'tableurxl:uploadexcelnotesmat' codemat=matiere.codeapogee  %}"
                            class="btn bg-danger text-white">
                            {{ matiere.codeapogee }}
                            <a href="{% url 'tableurxl:uploadexcelnotesmat2' codemat=matiere.codeapogee  %}"
                                class="btn bg-danger text-white">
                                {{ matiere.codeapogee }} ITEM CC
                            </a>
                    </th>
                    <td>{{ matiere.nom }}</td>
                    <td>{{ matiere.coefcc1 }}</td>
                    <td>{{ matiere.coefcc2 }}</td>
                    <td>{{ matiere.coefcc3 }}</td>

                </tr>
                {% endfor %}

            </table>

        </div>


    </div>
</div>
{% endblock content %}

matiere/templates/matiere/notesmatiere.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2> {{ templateData.matiere.codeapogee }} : {{ templateData.matiere.nom }}</h2>
                {% if perms.gdjury.add_matiere %}

                <a href="{% url 'matiere:editnotesmatiere' templateData.matiere.codeapogee 'alt'  1  %}"
                    class="btn bg-success text-white">
                    Entrez notes alternants {{ templateData.matiere.codeapogee }}
                </a>
                <a href="{% url 'matiere:editnotesmatiere' templateData.matiere.codeapogee 'nonalt' 1  %}"
                    class="btn bg-success text-white">
                    Entrez notes non alternants {{ templateData.matiere.codeapogee }}
                </a>

                {% endif %}

                <hr />
            </div>
        </div>
        <div class="row">

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">rang</th>
                        <th scope="col">nom</th>
                        <th scope="col">prénom</th>
                        <th scope="col">moyenne</th>
                        <th scope="col">CC1</th>
                        <th scope="col">CC2</th>
                        <th scope="col">CC3</th>
                        <th scope="col">Point Jury</th>
                        <th scope="col">Statut</th>
                    </tr>
                </thead>
                {% for inscrimat in templateData.listeinscritmat %}
                <tr>
                    <th scope="row">{{ inscrimat.rang }}</th>
                    <td>{{ inscrimat.inscriptiondiplome.etudiant.nom }}</td>
                    <td>{{ inscrimat.inscriptiondiplome.etudiant.prenom }}</td>
                    <td class="fw-bold">{{ inscrimat.moyenne|floatformat:2 }}</td>
                    <td>{{inscrimat.notecc1|floatformat:2 }}</td>
                    <td>{{inscrimat.notecc2|floatformat:2 }}</td>
                    <td>{{inscrimat.notecc3|floatformat:2 }}</td>
                    <td>{{inscrimat.pointjury|floatformat:2 }}</td>
                    <td>{{inscrimat.statut }}</td>
                </tr>
                {% endfor %}

            </table>

        </div>


    </div>
</div>
{% endblock content %}