comptes/urls.py
from django.urls import path
from . import views

app_name = "comptes"


urlpatterns =[ 
    path('login/',views.login, name ='login'),
    path('logout/',views.logout, name ='logout'),

 ]

diplome/urls.py
from django.urls import path
from . import views
app_name = "diplome"

urlpatterns = [
    path('annee/', views.indexannee, name='indexannee'),
    path('S2/', views.S2, name="valideS2"),
    path('creationannee/', views.creationannee, name='creationannee'),


]

docpdf/urls.py
from django.urls import path
from . import views
app_name = "docpdf"
urlpatterns = [
    path('avispoursuiteetude/tous/', views.avispoursuitetous, name='avispoursuitetous'),
    
    path('avispoursuiteetude/<int:id>/', views.avispoursuite, name='avispoursuite'),



]

gestiondejury/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('etudiants/',include('etudiant.urls')),
    path('comptes/', include('comptes.urls')),
    path('matieres/', include('matiere.urls')),
    path('adminjury/', include('adminjury.urls')),
    path('jury/', include('jury.urls')),
    path('excel/',include('tableurxl.urls')),
    path('diplome/',include('diplome.urls')),
    path('docpdf/',include('docpdf.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
]

jury/urls.py
from django.urls import path
from . import views

app_name="jury"


urlpatterns = [
    path('',views.jury, name='indexjury'),
    path('S5/<int:rang>/', views.juryS5,name='juryS5'),
    path('diplome/<int:rang>/', views.jurydiplome,name='juryDiplome'),
    path('decisionmat/<int:etud>/<int:mat>/', views.decisionmat, name='decisionmat' ),
    path('decisionS5/<int:etud>/', views.decisionS5, name='decisionS5' ),
    path('decisionS6/<int:etud>/', views.decisionS6, name='decisionS6' ),
    path('decisiondiplome/<int:etud>/', views.decisiondiplome, name='decisiondiplome' ),
    path('avis/<int:etud>/', views.avisPoursuiteEtude, name='avispoursuite' ),

]

gestiondejury/templates/base.html
<!DOCTYPE html>
<html lang="fr">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ templateData.titre }}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

</head>

<body>

    {% if user.is_authenticated %}
    {% include "./navbar.html" %}
    {% endif %}

    <div class="container mt-5 p-5">
        <h4> {{ anneesession }} : {{ diplome }}</h4>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div class="alert 
        {% if message.tags %}
          alert-{{ message.tags }}
        {% endif %}">
                {{ message|linebreaksbr }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% block content %}

        {% endblock content %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
    {% if perms.gdjury.add_etudiant %}
    <footer>
        {% include "./navbaradmin.html" %}
    </footer>
    {% endif %}
</body>



</html>

gestiondejury/templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top bg-body-tertiary">
    <div class="container-fluid">


        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'matiere:index' %}">Matières</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Etudiant
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'etudiant:index' %}">Etudiants</a></li>
                        <li><a class="dropdown-item" href="{% url 'etudiant:liste' alt='nonalt' %}">Non
                                alternants</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'etudiant:liste' alt='alt' %}">Alternants</a></li>
                        <li><a class="dropdown-item" href="{% url 'etudiant:liste' alt='neu' %}">N.E.U.</a></li>
                        <li><a class="dropdown-item" href="{% url 'etudiant:liste' alt='redoubl' %}">Redoublants</a>
                        </li>
                    </ul>

                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Jury
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'jury:juryS5' 1 %}">Jury S5 Non Alternants</a></li>
                        <li><a class="dropdown-item" href="{% url 'jury:juryS5' 1 %}?alt=true">Jury S5 Alternants</a>
                        </li>

                    </ul>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'diplome:indexannee' %}">Année</a>
                </li>
            </ul>

            <a href="{% url 'comptes:logout' %}" class="btn btn-primary btn-lg active" role="button"
                aria-pressed="true">Déconnexion : {{ user.username }}</a>

        </div>
    </div>
</nav>

gestiondejury/templates/navbaradmin.html
<nav class="navbar fixed-bottom navbar-light bg-light">
    <div class="container">



        <div class="btn-group dropup">
            <button type="button" class="btn btn-secondary">
                Notes excel
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown" aria-expanded="false">

                <span class="visually-hidden">menu admin 1</span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'matiere:listematexcel' sem='S5' %}">Matières S5</a></li>

                <li><a class="dropdown-item" href="{% url 'matiere:listematexcel' sem='S6' %}">Matières S6</a></li>

            </ul>
        </div>

        <div class="btn-group dropup">
            <button type="button" class="btn btn-secondary">
                Jury admin S5
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown" aria-expanded="false">

                <span class="visually-hidden">menu admin 1</span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item"
                        href="{% url 'adminjury:calculmoyennesemestre' sem='S5' alt='nonalt'  %}">Calcul moyenne
                        matières
                        S5 Non Alternants</a></li>
                <li><a class="dropdown-item" href="{% url 'adminjury:calculsemestre' sem='S5' alt='nonalt'  %}">Calcul
                        moyenne S5 Non Alternants</a></li>
                <li><a class="dropdown-item"
                        href="{% url 'adminjury:calculmoyennesemestre' sem='S5' alt='alt'  %}">Calcul moyenne matières
                        S5 Alternants</a></li>
                <li><a class="dropdown-item" href="{% url 'adminjury:calculsemestre' sem='S5' alt='alt'  %}">Calcul
                        moyenne S5 Alternants</a></li>
                <li><a class="dropdown-item" href="{% url 'adminjury:nbrinscritmatiere' %}">Calcul nbre d'inscrits</a>
                </li>
            </ul>
        </div>
        <div class="btn-group dropup">
            <button type="button" class="btn btn-secondary">
                Jury admin S6
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown" aria-expanded="false">

                <span class="visually-hidden">menu admin 2</span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item"
                        href="{% url 'adminjury:calculmoyennesemestre' sem='S6' alt='nonalt'  %}">Calcul moyenne
                        matières
                        S6 Non Alternants</a></li>
                <li><a class="dropdown-item" href="{% url 'adminjury:calculsemestre' sem='S6' alt='nonalt'  %}">Calcul
                        moyenne S6 Non Alternants</a></li>
                <li><a class="dropdown-item"
                        href="{% url 'adminjury:calculmoyennesemestre' sem='S6' alt='alt'  %}">Calcul moyenne matières
                        S6 Alternants</a></li>
                <li><a class="dropdown-item" href="{% url 'adminjury:calculsemestre' sem='S6' alt='alt'  %}">Calcul
                        moyenne S6 Alternants</a></li>
            </ul>
        </div>
        <div class="btn-group dropup">
            <button type="button" class="btn btn-secondary">
                Gestion etudiant
            </button>
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split"
                data-bs-toggle="dropdown" aria-expanded="false">

                <span class="visually-hidden">menu admin 3</span>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'etudiant:addetudiant' %}">Nouvel étudiant</a></li>
                <li><a class="dropdown-item" href=" {% url 'etudiant:addinscriptiondipl' %} ">Inscription diplome</a>
                <li><a class="dropdown-item" href=" {% url 'etudiant:indexetudiantadmin' %} ">Liste etudiant pour
                        insciption matières</a>
                </li>
                <li><a class="dropdown-item" href=" {% url 'docpdf:avispoursuitetous' %} ">
                        Edition Avis Poursuite</a>
                </li>
            </ul>
        </div>
    </div>

</nav>