gestiondejury/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('etudiants/',include('etudiant.urls')),
    path('comptes/', include('comptes.urls')),
    path('matieres/', include('matiere.urls')),
    path('adminjury/', include('adminjury.urls')),
    path('jury/', include('jury.urls')),
    path('excel/',include('tableurxl.urls')),
    path('diplome/',include('diplome.urls')),
    path('docpdf/',include('docpdf.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
]

jury/urls.py
from django.urls import path
from . import views

app_name="jury"


urlpatterns = [
    path('',views.jury, name='indexjury'),
    path('S5/<int:rang>/', views.juryS5,name='juryS5'),
    path('diplome/<int:rang>/', views.jurydiplome,name='juryDiplome'),
    path('decisionmat/<int:etud>/<int:mat>/', views.decisionmat, name='decisionmat' ),
    path('decisionS5/<int:etud>/', views.decisionS5, name='decisionS5' ),
    path('decisionS6/<int:etud>/', views.decisionS6, name='decisionS6' ),
    path('decisiondiplome/<int:etud>/', views.decisiondiplome, name='decisiondiplome' ),
    path('avis/<int:etud>/', views.avisPoursuiteEtude, name='avispoursuite' ),

]

matiere/urls.py
from django.urls import path,re_path
from . import views
app_name = "matiere"
urlpatterns = [
    path('', views.indexmatiere, name='index'),
    path('notes/<str:code>', views.notes,name='notes'),
    path('editnotes/<str:code>/<int:etudiant>', views.editnotes,name='editnotes'),
    re_path(r'^editnotesmatiere/(?P<code>KM[A-Z]{4}\d{2})/(?P<alt>(alt|nonalt))/(?P<etudiantalpha>\d+)$',views.editnotesmatiere,name = 'editnotesmatiere'),
    path("excelnotes/<str:sem>",views.listematexcel,name="listematexcel")

]

jury/models.py
from django.db import models
from diplome.models import Diplome,Anneeuniv

# Create your models here.
class Jury(models.Model):
    id = models.AutoField(primary_key=True)
    datejury = models.DateTimeField(null=True)
    anneeuniv=models.ForeignKey(Anneeuniv,on_delete=models.CASCADE)
    diplome=models.ForeignKey(Diplome,on_delete=models.CASCADE)
    semestre =models.CharField(max_length=3)
    alternant = models.BooleanField()
    fini = models.BooleanField(default=False)

    def __str__(self):
        nom =self.diplome.nom+' : '+ self.anneeuniv.anneeuniv
        if self.alternant:
            nom += ": alternants"
        return nom

jury/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required,permission_required
from diplome.models import Anneeuniv,Diplome
from etudiant.models import Inscriptiondiplome,Inscriptionmat,Etudiant
from django.contrib import messages
from django.urls import reverse
from urllib.parse import urlencode
from .models import Jury
import  datetime
# Create your views here.

@login_required
def jury(request):
    listeJurys = Jury.objects.all().order_by("-datejury")
    templateData = {}
    templateData ['titre']= "Jury"
    templateData ['listeJurys']= listeJurys
    return render (request,'jury/listejurys.html'
                  ,{'templateData': templateData} )


@login_required
def jurydiplome(request,rang):
    anneeuniv = Anneeuniv.objects.get(encours = True)
    alt = request.GET.get('alt','false').lower()=='true'
    codeAPOGEE = request.GET.get('codeAPOGEE',"K3MKGE")
    diplomejury = Diplome.objects.get(codeapogee= codeAPOGEE)
    listeInscriptionDiplome =Inscriptiondiplome.objects.filter(diplome=diplomejury,
                                                      anneeuniv=anneeuniv,
                                                      alternant = alt)
    nbreetudiants = len( listeInscriptionDiplome)
    listeInscriptionDiplome=listeInscriptionDiplome.order_by("-noteAnnee")   
    etudiant =listeInscriptionDiplome[rang-1].etudiant
    inscridipl = listeInscriptionDiplome.get(etudiant=etudiant,anneeuniv=anneeuniv)

    listeinsdiplomeetu = Inscriptiondiplome.objects.filter(etudiant=etudiant)
    listeinsdiplomeetu =listeinsdiplomeetu.order_by('anneeuniv__datedebut')
    ListeInscritmatS6 =Inscriptionmat.objects.filter(inscriptiondiplome__etudiant=etudiant,matiere__semestre ="S6" )
    ListeInscritmatS5 =Inscriptionmat.objects.filter(inscriptiondiplome__etudiant=etudiant,matiere__semestre ="S5" )
    
    templateData = {}
    templateData ['titre']= "Jury diplome : " +anneeuniv.anneeuniv
    templateData ['annee']=anneeuniv
    templateData ['diplome']=diplomejury
    templateData ['etudiant']=etudiant
    templateData ['listeinsdiplome']=listeinsdiplomeetu
    templateData ['listeinscritmatS5']=ListeInscritmatS5
    templateData ['listeinscritmatS6']=ListeInscritmatS6
    templateData ['insdiplome']=inscridipl   
    templateData ['nbreetudiants']=nbreetudiants 
    templateData ['juryS5']=False

    return render (request,'jury/jurydiplomeetudiant.html'
                  ,{'templateData': templateData} )

@login_required
def juryS5(request,rang):
    anneeuniv = Anneeuniv.objects.get(encours = True)

    alt = request.GET.get('alt','false').lower()=='true'
    codeAPOGEE = request.GET.get('codeAPOGEE',"K3MKGE")
    diplomejury = Diplome.objects.get(codeapogee= codeAPOGEE)
    listeInscriptionDiplome =Inscriptiondiplome.objects.filter(diplome=diplomejury,
                                                      anneeuniv=anneeuniv,
                                                      alternant = alt)
    nbreetudiants = len( listeInscriptionDiplome)
    lpoursuiteEtude=[]
    liste = listeInscriptionDiplome.filter(avispoursuite ="TF")
    lpoursuiteEtude.append(len(liste))
    lpoursuiteEtude.append(len(liste)/ nbreetudiants *100)
    liste = listeInscriptionDiplome.filter(avispoursuite ="FA")
    lpoursuiteEtude.append(len(liste))
    lpoursuiteEtude.append(len(liste)/ nbreetudiants *100)
    liste = listeInscriptionDiplome.filter(avispoursuite ="RE")
    lpoursuiteEtude.append(len(liste))
    lpoursuiteEtude.append(len(liste)/ nbreetudiants *100)
    liste = listeInscriptionDiplome.filter(avispoursuite ="DE")
    lpoursuiteEtude.append(len(liste))
    lpoursuiteEtude.append(len(liste)/ nbreetudiants *100)



    listeInscriptionDiplome=listeInscriptionDiplome.order_by("-noteSem1")   
    etudiant =listeInscriptionDiplome[rang-1].etudiant
    inscridipl = listeInscriptionDiplome.get(etudiant=etudiant,anneeuniv=anneeuniv)

    listeinsdiplomeetu = Inscriptiondiplome.objects.filter(etudiant=etudiant)
    listeinsdiplomeetu =listeinsdiplomeetu.order_by('anneeuniv__datedebut')
    ListeInscritmat =Inscriptionmat.objects.filter(inscriptiondiplome__etudiant=etudiant,matiere__semestre ="S5" ).order_by("matiere__nom")
    
    templateData = {}
    templateData ['titre']= "Jury S5 : " +anneeuniv.anneeuniv
    templateData ['annee']=anneeuniv
    templateData ['diplome']=diplomejury
    templateData ['etudiant']=etudiant
    templateData ['listeinsdiplome']=listeinsdiplomeetu
    templateData ['listeinscritmatS5']=ListeInscritmat
    templateData ['insdiplome']=inscridipl   
    templateData ['nbreetudiants']=nbreetudiants 
    templateData ['juryS5']=True
    templateData ['poursuite']= lpoursuiteEtude
    return render (request,'jury/juryS5etudiant.html'
                  ,{'templateData': templateData} )


@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def decisionmat(request,etud,mat):
    anneeencours = Anneeuniv.objects.get(encours =True)
    insmatetu = get_object_or_404(Inscriptionmat, inscriptiondiplome__etudiant = etud,matiere = mat,inscriptiondiplome__anneeuniv = anneeencours)
    insmatetu.statut = "ADJ"
    insmatetu.decisionmat = datetime.datetime.now()
    insmatetu.save()
    insDiplome = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)
   
    messages.success(request, "ADJ effectué" )
    if  insDiplome.alternant:
        if anneeencours.S2:
            rang = insDiplome.rangAnnee
            base_url = reverse('jury:juryDiplome',kwargs={'rang': rang})
        else:
            rang = insDiplome.rangSem1
            base_url = reverse('jury:juryS5',kwargs={'rang': rang})
        base_url = reverse('jury:juryS5',kwargs={'rang': rang})
        query_string =urlencode({'alt':'true'})
        url = f'{base_url}?{query_string}'
        return redirect(url) 

    if anneeencours.S2:
        rang = insDiplome.rangAnnee
        return redirect('jury:juryDiplome', rang = rang)
    else:
        rang = insDiplome.rangSem1
        return redirect('jury:juryS5', rang = rang)

@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def decisionS5(request,etud):
    anneeencours = Anneeuniv.objects.get(encours =True)
    insS5etu = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)
    insS5etu.statutS1 = 'ADJ'
    insS5etu.datedecisionS1=datetime.datetime.now()
    insS5etu.save()
    
    messages.success(request, "ADJ S5 effectué" )
    insDiplome = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)

    if insDiplome.alternant:
        if anneeencours.S2:
            rang = insS5etu.rangAnnee
            base_url = reverse('jury:juryDiplome',kwargs={'rang': rang})
        else:
            rang = insS5etu.rangSem1
            base_url = reverse('jury:juryS5',kwargs={'rang': rang})
        query_string =urlencode({'alt':'true'})
        url = f'{base_url}?{query_string}'
        return redirect(url)
     
    if anneeencours.S2: 
        rang = insS5etu.rangAnnee

        return redirect('jury:juryDiplome', rang = rang)
    else:
        rang = insS5etu.rangSem1
        return redirect('jury:juryS5', rang = rang)

@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def decisionS6(request,etud):
    anneeencours = Anneeuniv.objects.get(encours =True)
    insS6etu = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)
    insS6etu.statutS2 = 'ADJ'
    insS6etu.datedecisionS2=datetime.datetime.now()
    insS6etu.save()
    rang = insS6etu.rangAnnee
    messages.success(request, "ADJ S6 effectué" )
    insDiplome = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)

    if insDiplome.alternant:
        base_url = reverse('jury:juryS6',kwargs={'rang': rang})
        query_string =urlencode({'alt':'true'})
        url = f'{base_url}?{query_string}'
        return redirect(url) 

    return redirect('jury:juryDiplome', rang = rang)

@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def decisiondiplome(request,etud):
    anneeencours = Anneeuniv.objects.get(encours =True)
    insetu = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)
    insetu.statutDipl = 'ADJ'
    insetu.datedecisionDipl=datetime.datetime.now()
    insetu.save()
    rang = insetu.rangAnnee
    messages.success(request, "ADJ diplome effectué" )
    insDiplome = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)

    if insDiplome.alternant:
        base_url = reverse('jury:juryS6',kwargs={'rang': rang})
        query_string =urlencode({'alt':'true'})
        url = f'{base_url}?{query_string}'
        return redirect(url) 

    return redirect('jury:juryDiplome', rang = rang)


@login_required
@permission_required('gestiondejury.change_etudiant', raise_exception = True)
def avisPoursuiteEtude(request,etud):
    anneeencours = Anneeuniv.objects.get(encours =True)
   

    etudiant = Etudiant.objects.get(id=etud)
    insAvisetu = get_object_or_404(Inscriptiondiplome, etudiant = etud,anneeuniv = anneeencours)

    avis = request.GET.get('avis') 
    if avis == 'Tf':
         insAvisetu.avispoursuite = "TF"
    elif  avis == 'Fa':
         insAvisetu.avispoursuite = "FA"
    elif avis == 'Re':
          insAvisetu.avispoursuite = "RE"
    elif avis == 'De' :      
         insAvisetu.avispoursuite = "DE"
    insAvisetu.save()

    rang = insAvisetu.rangSem1
    messages.success(request, "Avis de poursuite d'étude réalisé" )
    if insAvisetu.alternant:
        base_url = reverse('jury:juryS5',kwargs={'rang': rang})
        query_string =urlencode({'alt':'true'})
        url = f'{base_url}?{query_string}'
        return redirect(url)       


    return redirect('jury:juryS5', rang = rang)

jury/templates/jury/juryS5etudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>{{ templateData.diplome.codeapogee }} {{ templateData.diplome.nom }}</h2>
                <hr>
                <h2>Jury S5 : {{ templateData.annee.anneeuniv}}</h2>

            </div>
            <div class="col-3">
                {% if templateData.insdiplome.rangSem1 != 1 %}
                {% if templateData.insdiplome.alternant %}
                <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryS5' templateData.insdiplome.rangSem1|add:-1 %}?alt=true"
                    role="button">Précédent</a>
                {% else %}
                <a class="btn btn-primary btn-sm" href="{% url 'jury:juryS5' templateData.insdiplome.rangSem1|add:-1 %}"
                    role="button">Précédent</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="col-3">
                {% if templateData.insdiplome.rangSem1 != templateData.nbreetudiants %}
                {% if templateData.insdiplome.alternant %} <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryS5' templateData.insdiplome.rangSem1|add:1 %}?alt=true" role="button">
                    Suivant</a>
                {% else %}
                <a class="btn btn-primary btn-sm" href="{% url 'jury:juryS5' templateData.insdiplome.rangSem1|add:1 %}"
                    role="button">Suivant</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="row">
                <div class="col-3 align-self-start">
                    {% include "etudiant/cadreetudiant.html" %}
                </div>
                <div class="col align-self-start">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Semestre</th>
                                <th>Moyenne</th>
                                <th>Statut</th>
                                <th>Date decision</th>
                                <th>Rang</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>
                                    <h4>S5</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteSem1|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutS1 }} </h4>


                                </th>
                                <th> {% if templateData.insdiplome.statutS1 == 'ADJ' %}
                                    {{ templateData.insdiplome.datedecisionS1|date:"SHORT_DATE_FORMAT" }}
                                    {% endif %}
                                    {% if perms.gestiondejury.change_etudiant %}
                                    {% if templateData.insdiplome.statutS1 == "AJ" %}
                                    <a class="btn btn-success"
                                        href="{% url 'jury:decisionS5' templateData.insdiplome.etudiant.id %}"
                                        role="button">ADJ
                                        S5</a>
                                    {% endif %}
                                    {% endif %}
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangSem1 }}/{{ templateData.nbreetudiants }}</h4>
                                </th>
                            </tr>
                            {% if templateData.S2 %}
                            <tr>
                                <th>
                                    <h4>S6</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteSem2|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutS2 }} </h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangSem2 }}</h4>
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <h4>Année</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteAnnee|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutDipl }} </h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangAnnee }}</h4>
                                </th>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>

                    {% if perms.gestiondejury.change_etudiant %}
                    {% include "jury/tablejuryPresident.html" %}
                    {% else %}

                    {% include "jury/tablejuryMembre.html" %}
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
    {% if perms.gestiondejury.change_etudiant %}
    <div class="row justify-content-center">

        <h3>Avis de poursuite d'étude</h3>
        <div class="col-3">
            <a class="btn btn-success"
                href="{% url 'jury:avispoursuite' templateData.insdiplome.etudiant.id  %}?avis=Tf" role="button">Très
                favorable</a>
            nbr : {{ templateData.poursuite.0}}/{{ templateData.poursuite.1|floatformat:2}}%
        </div>

        <div class="col-3">
            <a class="btn btn-success"
                href="{% url 'jury:avispoursuite' templateData.insdiplome.etudiant.id  %}?avis=Fa"
                role="button">Favorable</a>
            nbr : {{ templateData.poursuite.2}}/{{ templateData.poursuite.3|floatformat:2}}%
        </div>
        <div class="col-3">
            <a class="btn btn-success"
                href="{% url 'jury:avispoursuite' templateData.insdiplome.etudiant.id  %}?avis=Re"
                role="button">Réservé</a>
            nbr : {{ templateData.poursuite.4}}/{{ templateData.poursuite.5|floatformat:2}}%
        </div>
        <div class="col-3">
            <a class="btn btn-danger" href="{% url 'jury:avispoursuite' templateData.insdiplome.etudiant.id  %}?avis=De"
                role="button">Défavorable</a>
            nbr : {{ templateData.poursuite.6}}/{{ templateData.poursuite.7|floatformat:2}}%
        </div>

    </div>
    {% endif %}
</div>
{% endblock content %}

jury/templates/jury/jurydiplomeetudiant.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>{{ templateData.diplome.codeapogee }} {{ templateData.diplome.nom }}</h2>
                <hr>
                <h2>Jury S5 : {{ templateData.annee.anneeuniv}}</h2>

            </div>
            <div class="col-3">
                {% if templateData.insdiplome.rangSem1 != 1 %}
                {% if templateData.insdiplome.alternant %}
                <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryS5' templateData.insdiplome.rangAnnee|add:-1 %}?alt=true"
                    role="button">Précédent</a>
                {% else %}
                <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryDiplome' templateData.insdiplome.rangAnnee|add:-1 %}"
                    role="button">Précédent</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="col-3">
                {% if templateData.insdiplome.rangSem1 != templateData.nbreetudiants %}
                {% if templateData.insdiplome.alternant %} <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryS5' templateData.insdiplome.rangAnnee|add:1 %}?alt=true" role="button">
                    Suivant</a>
                {% else %}
                <a class="btn btn-primary btn-sm"
                    href="{% url 'jury:juryDiplome' templateData.insdiplome.rangAnnee|add:1 %}"
                    role="button">Suivant</a>
                {% endif %}
                {% endif %}
            </div>
            <div class="row">
                <div class="col-3 align-self-start">
                    {% include "etudiant/cadreetudiant.html" %}
                </div>
                <div class="col align-self-start">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Semestre</th>
                                <th>Moyenne</th>
                                <th>Statut</th>
                                <th>Date decision</th>
                                <th>Rang</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th>
                                    <h4>S5</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteSem1|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutS1 }} </h4>


                                </th>
                                <th> {% if templateData.insdiplome.statutS1 == 'ADJ' %}
                                    {{ templateData.insdiplome.datedecisionS1|date:"SHORT_DATE_FORMAT" }}
                                    {% endif %}
                                    {% if perms.gestiondejury.change_etudiant %}
                                    {% if templateData.insdiplome.statutS1 == "AJ" %}
                                    <a class="btn btn-success"
                                        href="{% url 'jury:decisionS5' templateData.insdiplome.etudiant.id %}"
                                        role="button">ADJ
                                        S5</a>
                                    {% endif %}
                                    {% endif %}
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangSem1 }}/{{ templateData.nbreetudiants }}</h4>
                                </th>
                            </tr>

                            <tr>
                                <th>
                                    <h4>S6</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteSem2|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutS2 }} </h4>
                                </th>
                                <th> {% if templateData.insdiplome.statutS2 == 'ADJ' %}
                                    {{ templateData.insdiplome.datedecisionS1|date:"SHORT_DATE_FORMAT" }}
                                    {% endif %}
                                    {% if perms.gestiondejury.change_etudiant %}
                                    {% if templateData.insdiplome.statutS2 == "AJ" %}
                                    <a class="btn btn-success"
                                        href="{% url 'jury:decisionS6' templateData.insdiplome.etudiant.id %}"
                                        role="button">ADJ
                                        S6</a>
                                    {% endif %}
                                    {% endif %}
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangSem2 }}/{{ templateData.nbreetudiants }}</h4>
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <h4>Année</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.noteAnnee|floatformat:2 }}</h4>
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.statutDipl }} </h4>
                                </th>
                                <th> {% if templateData.insdiplome.statutDipl == 'ADJ' %}
                                    {{ templateData.insdiplome.datedecisionS1|date:"SHORT_DATE_FORMAT" }}
                                    {% endif %}
                                    {% if perms.gestiondejury.change_etudiant %}
                                    {% if templateData.insdiplome.statutDipl == "AJ" %}
                                    <a class="btn btn-success"
                                        href="{% url 'jury:decisiondiplome' templateData.insdiplome.etudiant.id %}"
                                        role="button">ADJ
                                        Diplome</a>
                                    {% endif %}
                                    {% endif %}
                                </th>
                                <th>
                                    <h4>{{ templateData.insdiplome.rangAnnee }}/{{ templateData.nbreetudiants }}</h4>
                                </th>
                            </tr>

                        </tbody>
                    </table>

                    {% if perms.gestiondejury.change_etudiant %}
                    {% include "jury/tablejuryPresident.html" %}
                    {% else %}

                    {% include "jury/tablejuryMembre.html" %}
                    {% endif %}
                </div>
            </div>

        </div>
    </div>

</div>
{% endblock content %}

jury/templates/jury/listejurys.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="p-3">
    <div class="container">
        <div class="row mt-3">
            <div class="col mx-auto mb-3">
                <h2>Liste des jurys</h2>
                <hr />
                <table class="table">

                    <tr>

                        <th scope="col">Diplome</th>
                        <th scope="col">Date</th>
                        <th scope="col"> Alternant</th>
                        <th scope="col"> Statut</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for jury in templateData.listeJurys %}

                        <tr class="{% cycle 'table-light' '' %}">

                            <td> {{ jury.diplome.nom }} {{ jury.semestre }}</td>
                            <td> {{ jury.datejury|date:"SHORT_DATE_FORMAT" }} {{ jury.datejury|time:"H:i" }}</td>
                            <td>{% if jury.alternant == True %} alternant
                                {% else %}
                                non alternant
                                {% endif %}
                            </td>
                            <td>{% if jury.fini == True %}
                                clos
                                {% else %}
                                En cours
                                {% endif %}
                            </td>


                        </tr>
                        {% endfor %}
                    </tbody>



                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}